### ISSUE TITLE
Use containers to enforce environment similarity

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#11]
Currently, my build and deploy system relies on the server environment being set up correctly, and nothing enforces consistency between my local machine and production. Use contaienrs

Blocked on Bazel, since Docker containers are pretty easy to generate using Bazel's Docker integration.

**Comment by drvan** [comment]
Could a Dockerfile suffice in the meantime?

**Comment by jakevoytko** [comment]
I don't see a reason to do it twice
