### ISSUE TITLE
Multi-line learning is broken

### ISSUE THREAD

**Issue by aetimmes** [jakevoytko/crbot#16]
Steps to reproduce:

[9:48 PM] Timmes: ?learn was
What a save!
What a save!
What a save!
Chat disabled for 1 second.
What a save!
Chat disabled for 4 seconds.

Expected output:

[9:48 PM] DaaSbot: Learned about was
[9:48 PM] Timmes: ?was
[9:48 PM] DaaSbot:
What a save!
What a save!
What a save!
Chat disabled for 1 second.
What a save!
Chat disabled for 4 seconds.

Actual output:

[9:48 PM] DaaSbot: Learned about was
What
[9:48 PM] Timmes: ?was
[9:48 PM] Timmes: uhhhhh bug report +Jake +Arc

**Comment by drvan** [comment]
Is it ever. I'm not entirely sure what happened, but it looks like part of the response was interpreted as part of the call. Getting a list of commands returns the following:
```
 - ?war
 - ?was
What
 - ?whitney
```

Calling ?was does nothing. @jakevoytko can you take a look at Redis to see what's actually stored there?

**Comment by jakevoytko** [comment]
Fixed by b5128f315d765de3557de1d1b35c29bb1411b616

**Comment by aetimmes** [comment]
Thanks all!
