### ISSUE TITLE
Start responses with $1

### ISSUE THREAD

**Issue by aetimmes** [jakevoytko/crbot#2]
I'd like it if the restrictions on first character of response could be relaxed to include $1. For example:

?learn chicago $1 used to work in Chicago, the old department store,
$1 used to work in Chicago, I don't work there anymore.

**Comment by jakevoytko** [comment]
@andrew-timmes `crbot` also only substitutes the first $1; I don't want to relax this because I think it would be an avenue of attack by our lovely friends. Do you still want this, in light of that?

**Comment by aetimmes** [comment]
How so?

**Comment by jakevoytko** [comment]
```
?learn ha $1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1$1
?ha hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha
```

**Comment by aetimmes** [comment]
What if we were to put a finite cap on the number of $1 recurrences?

**Comment by aetimmes** [comment]
Or would a custom command for my RL spam command be a better way to implement this?
