### ISSUE TITLE
?vote function

### ISSUE THREAD

**Issue by aetimmes** [jakevoytko/crbot#20]
I'd like a ?vote function to emulate the behavior of the vote function in CS:GO.

* There can be at most one vote in progress.
* Voting will last for a set period of time or until a simple majority is achieved.
* Each user can only vote once. No waffling!
* If there is no vote in progress:
  * Calling ?vote with arguments will call a vote on the arguments (ie ?vote kick @Trillian). It will also cast a "yes" vote for the calling user on that vote.
  * Calling ?vote with no arguments will display helptext on how to use ?vote.
* If there is a vote in progress:
  * ?vote will accept inputs of f1|yes and f2|no. 
  * If the user hasn't already voted, the command will increment the yes/no counters. 
  * The bot will respond to these commands with the current vote count. 
  * Any other arguments to a ?vote while a ?vote is active (including duplicate votes) will display helptext that includes the current vote topic, the vote count and the time remaining.
* At the end of the time period or when a majority is reached, the bot will print the results of the vote to the channel.
* The bot will then time out the ?vote function for a set period of time to prevent last-minute too-late votes from starting a new vote.

**Comment by jakevoytko** [comment]
To refine the spec:

**Parsing**
* `?vote $1` will start a vote
* If `$1` is empty, the program will respond with the result of `?help vote`
* `?f1`, `?yes` will record the user as for the measure, and `?f2` and `?no` will record the user's vote as against
* If a vote is not in progress, `?f1`, `?yes`, `?f2`, and `?no` will print a help message. This will stomp any existing commands for these

**Vote behavior**
* One vote in progress at a time, _per channel_. Calling a vote while a vote is in progress will print the current status of the vote
* When a vote is recorded, it will print the current status of the vote
* Votes cannot be called in private channels
* Voting period is 30 minutes
* When the vote has terminated, it will at-include everyone that voted and tell them the outcome.
* The initial message will use `@here` to alert present people of a vote. Followup messages will not at-include people.
* 5 votes for, or 5 against, will be considered a successful vote. This will allow smaller channels (GOT chat) to have a chance to pass a vote. V1 won't take server population size into account.
* Once a vote becomes successful, it will not terminate, to give popular votes a chance. It will go the full 30 minutes.
* A new vote can be called immediately after the conclusion of the previous one

**Planned for the future**
* `?votelist` will list all called votes in a gist. In the first version, all votes will be stored, but there will be no commands for accessing them.
* `?votelist @user` will show the votes called by the given user server-wide
* `?votelist recent` will print the results of the 5 most-recent votes server-wide

**Comment by jakevoytko** [comment]
The above has a beta version of vote to collect feedback. This doesn't have the timer that prints the result of the vote.

Feedback, based on my friends' experimentation with it:
- The vote should pass when it gets 5 total votes, not when Pass or Fail reach 5 votes.
- Notify when the vote closes
- Change "You voted yes/no" to "@person voted yes/no", since it's confusing when a lot of people vote
- Put the time remaining somewhere. Likely on all the count status lines (so ?f1/f2/yes/no would print "n minutes remaining", as well as votestatus)
- The vote should re-ping at some point.

I want to do all of these but re-ping (since it overlaps with ?votestatus)

**Comment by jakevoytko** [comment]
Also, experiment with switching the @here to @everyone and see how spammy that feels. I feel like that's something I'd need to make configurable per-server

**Comment by jakevoytko** [comment]
^ all of the above feedback (except notifying when the vote ends) have been addressed by the following commits: a0eb6e94161c59b255ddd245e4dc8495cabaee3c, 4b1f01d8bc2171ba6c640b58c7cbbfbc70edfd73, fb7364678c2d4eb6b7a8218225e4f8f0a47beecc, 8e19ff763c38fbae7115cf8ecb1f859d8cfe4743,  ecba345eb0bf7c80e30271fe1e9892bc155b74ae

**Comment by aetimmes** [comment]
add tagback to "You already voted" message, ie "@dgmavn#1234 already voted"

**Comment by jakevoytko** [comment]
Wrote 192597baa47652f791c7455d17014f84bbc1b8d1 to make all votes happen per-channel.

Remaining work:
- tagback to "you already voted"
- add a timer to ping the appropriate channel when a vote has ended
- populate the timer on startup

**Comment by jakevoytko** [comment]
860f6df1061b1ee35cc8bed620accd5203b68f4c addresses tagbacks

**Comment by jakevoytko** [comment]
d1a79fa65d03aaf86399916f9968dc721c68586c expires votes. I'm going to close this out and file a bug to have timers for all non-concluded votes restarted on startup.
