### ISSUE TITLE
Karma

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#26]
Allow users to upvote and downvote anything, using ?++ and ?--

Special hooks will be added to grok the @-annotation for users. Design TBD

**Comment by drvan** [comment]
Will there be limits on give-able karma? e.g. users can only give out _n_ units of karma per _t_ time period?

Per lili's decision, are we not allowing the ?++ and ?-- notation? or are we simply modifying the regex to allow it.

**Comment by jakevoytko** [comment]
Here's my initial spec:

`?++` and `?--` take an argument. If none is provided, then the help message is printed. If there's more than one word in the arguments, it only takes the first one.

If the argument is a username (either `@something` or `@something#1234`, the argument becomes `something`. Optional: same for channel names

It increments or decrements an internal counter, and on success of the write, prints out the message "$arg has been upvoted/downvoted. $arg now has $n karma"

If a username is in the message, there is no need to print it in the write response, since the user has already been alerted by the previous message.

The input validator will need to be relaxed to accept `?++` and `?--`. I may live to regret this, but I see no problem allowing it to just accept those characters holistically

**Comment by jakevoytko** [comment]
Oh! Optional - a command to display an arg's karma. Given that these are magic internet points, I don't think it's necessary.

**Comment by jakevoytko** [comment]
Also, to answer your question before, no karma limits. They're just magic internet points

**Comment by drvan** [comment]
Agree with everything except rate limiting. I think a rate limit might add some longevity to the features use. Even something as simple as "only one vote per hour" might be good enough. That being said, I think rate limiting could be added iteratively at a later date if needed.
