### ISSUE TITLE
Cross-compile binary for linux from mac

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#27]
Cross compilation is now supported

https://github.com/bazelbuild/rules_go/issues/70

Allow the binary to be built locally, and deployed and run remotely. This will avoid problems, like the one that I ran into where my local and remote versions of bazel were mismatched.

**Comment by excavador** [comment]
So, what the correct way to build linux binaries on mac for linux?

**Comment by jakevoytko** [comment]
^ per the above link, with the right version of bazel, `bazel build --cpu k8 $target` is supposed to build a Linux binary on Mac

**Comment by jakevoytko** [comment]
Closing this out, since docker's `go_image()` rule should replace the need for this. I don't believe this existed when I evaluated docker support in bazel 8 or 9 months ago, so... cool!
