### ISSUE TITLE
Implement ?remindme

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#38]
`?remind me to get $5 from Andrew tomorrow`
--> Would then PM you the next day, "Get $5 from Andrew"

Need to investigate things like date parsing. May not be realistic without knowing the schedule of the user (to avoid pinging them at awkward times)

This is a fake echo feature that somebody added that is actually used pretty often. Might be worth making a reminder system similar to Slack's

**Comment by aetimmes** [comment]
Do I owe you $5?

**Comment by jakevoytko** [comment]
I don't call *anybody* in our friend group Andrew, so no

**Comment by drvan** [comment]
https://github.com/olebedev/when may be of use - if we restrict looking for the date after a keyword (or better, a symbol), it might make the feature a little more robust and parsing a lot easier. e.g. `?remind me to get $5 from Andrew @ tomorrow`

**Comment by jakevoytko** [comment]
That's a great idea @drvan.
