### ISSUE TITLE
Moderation commands

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#43]
Design a system for moderating a server from within Discord.

There's a pretty large combinatorial explosion between all of the things that are possible, so this will require some investigation into what Discord already has to offer.

First step will be to enumerate all of the things that can/should be changed from within crbot.

Incomplete list:

**Nouns**: Users, channels, roles, nicknames, messages, ban lists
**Verbs**: Ignore, kick, ban, softban, ricklist, deafen, mute
**Relationships**: Channel membership, list membership

@aetimmes Do you have thoughts on what you would find useful as far as server moderation tools?

**Comment by aetimmes** [comment]
the two things I'm most interested in are granting/revoking permissions to roles in channels/channel categories and adding/removing roles to users.

There's also a bot in the Middle Age Noobs server that finds posts and associates users with roles based on their reactions to certain posts - they have server emotes for all the rocket league ranks and then assigns you to a server role based on which of those emotes you use to react to their welcome post. That strikes me as a cool self-service sort of thing that might improve on the role interface for normal users.
