### ISSUE TITLE
Use an automated deploy system

### ISSUE THREAD

**Issue by jakevoytko** [jakevoytko/crbot#9]
Currently, I `scp` these files onto my Linode, ssh in, and manually restart. Now that it's clear that I have to live with this for a while, it's time to upgrade. Ideally, I'd like a one-command build and deploy.

**Comment by drvan** [comment]
I could (fairly easily) write an Ansible playbook to do this - no agent required on your Linode box.

Edit: I'd need to know what exact commands you type to do this so I can abstract it out to Ansible modules.

**Comment by jakevoytko** [comment]
Haha, thanks for the offer, but this is going to be done in Chef, so that I get a better understanding of how Chef works.

`</questionable_decisions>`

**Comment by jakevoytko** [comment]
Per offline convos, Ansible looks like a better option.

**[9:32 PM]** **Chris**: sorry, what are you trying to do?

**[9:32 PM]** **Chris**: i haven't been following.

**[9:34 PM]** **Jake**: i think i'm trying to solve 2 problems - (1) pushing changes to DaaSbot, and (2) storing/updating the configuration of DaaSbot

**[9:35 PM]** **Jake**: currently (1) is done through scp, and (2) is not done at all, in the sense that i hand-updated everything on my linode

**[9:36 PM]** **Jake**: the implicit (3) is that i don't know any tools for these things, so i'm doing it in a Real Tool for the practice

**[9:37 PM]** **Ryan**: so chef and puppet are primarily intended to be used as follows: you have a master server, where you push your artifacts (configs, recipes, whatever)

**[9:37 PM]** **Ryan**: and n number of nodes that pretty much say 'hey chef/puppet master, my fqdn is foo.bar, what configs get applied to me?'

**[9:38 PM]** **Ryan**: and the puppet master/chef server will push the changes required to get the node to match the expected state

**[9:39 PM]** **Ryan**: so it would work for DaaS if you had a dedicated chef server/puppet master

**[9:39 PM]** **Ryan**: the alternative is known as chef solo

**[9:39 PM]** **Ryan**: where you copy the recipe and install chef

**[9:39 PM]** **Ryan**: and say 'hey chef, apply this state to the current machine'

**[9:39 PM]** **Jake**: yeah, that's the thing from the wikipedia page / intro youtube videos that made me think that this might work for me

**[9:39 PM]** **Ryan**: that more appropriately matches your use case, BUT it doesn't really solve the issue at hand: you're still going to have to scp the necessary files over

**[9:40 PM]** **Ryan**: i definitely think it would be a useful exercise

**[9:40 PM]** **Jake**: if i'm still scping files over, then what did chef/puppet accomplish?(edited)

**[9:41 PM]** **Ryan**: that's my point haha

**[9:41 PM]** **Ryan**: it would allow you to apply state to the machine

**[9:41 PM]** **Ryan**: e.g.

**[9:41 PM]** **Ryan**: this binary should be running

**[9:41 PM]** **Ryan**: redis should be running

**[9:41 PM]** **Ryan**: if this config file gets updated, bounce redis

**[9:41 PM]** **Ryan**: stuff like that

**[9:41 PM]** **Jake**: it doesn't actually push the changes itself?

**[9:41 PM]** **Jake**: for anything?

**[9:42 PM]** **Ryan**: it would push the changes, if it had a source to get the changes from, like a dedicated chef server

**[9:42 PM]** **Jake**: oh i see.

**[9:42 PM]** **Ryan**: but since in your situation, the chef 'server' and the 'client' are one in the same

**[9:42 PM]** **Jake**: wouldn't my laptop be the server and my vm be the client?

**[9:42 PM]** **Jake**: i want my laptop to be authoritative

**[9:43 PM]** **Ryan**: yes, but i'm not sure how to actually get chef to do that.. the VM would periodically reach out to your laptop for updates

**[9:43 PM]** **Jake**: i just want it to work when i trigger it from my laptop

**[9:43 PM]** **Jake**: i don't care about periodic updates

**[9:43 PM]** **Ryan**: right, that's why i suggested ansible

**[9:43 PM]** **Ryan**: you literally write the state in a yaml file

**[9:43 PM]** **Ryan**: and say 'ansible, go do this to this remote server'

**[9:43 PM]** **Ryan**: and it'll push configs, files, whatever it needs

**[9:44 PM]** **Jake**: nice

**[9:44 PM]** **Jake**: that sounds more like what i want

**[9:44 PM]** **Ryan**: but again, i'd defer to chris.. he really knows the ins and outs of chef

**[9:44 PM]** **Jake**: (and what i thought i could accomplish with chef)

**[9:44 PM]** **Ryan**: i'm sure it's not impossible in chef

**[9:44 PM]** **Ryan**: but i have a feeling you'd end up bending the tool to do things it wasn't really intended to do

**Comment by jakevoytko** [comment]
Chris countered with a sample Chef cookbook:

```
: # cookbooks/crbot/attributes/default.rb
defualt[:crbot][:foo] = "abc"
default[:crbot][:bar] = "def"

# cookbooks/crbot/files/default/crbot
# cookbooks/crbot/files/default/crbot/crbot.go
# cookbooks/crbot/files/default/crbot/ ...
# cookbooks/crbot/files/default/etc/init.d/crbot

# cookbooks/crbot/templates/default/crbot.json.erb
@my_json

# cookbooks/crbot/recipes/default.rb
%w{ crbot.go ... }.each do |f|
  cookbook_file f do
    source "crbot/#{f}"
    mode "0755"
    action :create
    notifies :restart, "service[crbot]"
  end
end
cookbook_file "/etc/init.d/crbot" do
  source "etc/init.d/crbot"
  mode "0755"
  action :create
end
config = { foo: node[:crbot][:foo], bar: node[:crbot][:bar] }
template "/etc/crbot.json" do
  source "crbot.json.erb"
  mode "0644"
  variables my_json: JSON.pretty_generate(conf)
  action :create
  notifies :restart, "sercive[crbot]"
end
service "crbot" do
  action [:enable, :start]
end

````

Gonna give this a shot sometime this week and see if it makes sense

**Comment by jakevoytko** [comment]
This was fixed with the ansible deploy scripts
